export const commands = {
  compress: (input) => input.startsWith('compress '),
  decompress: (input) => input.startsWith('decompress '),
  cd: (input) => input.startsWith('cd '),
  hash: (input) => input.startsWith('hash '),
  cat: (input) => input.startsWith('cat '),
  create: (input) => input.startsWith('add '),
  rename: (input) => input.startsWith('rn '),
  remove: (input) => input.startsWith('rm '),
  copy: (input) => input.startsWith('cp '),
  move: (input) => input.startsWith('mv '),
  ls: (input) => input === 'ls',
  up: (input) => input === 'up',
  homedir: (input) => input === 'os --homedir',
  username: (input) => input === 'os --username',
  architecture: (input) => input === 'os --architecture',
  cpus: (input) => input === 'os --cpus',
  eol: (input) => input === 'os --EOL',
};

